version: "3.8"

services:
  react_app:
    container_name: react-app-dev
    image: react-app
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
